version: '3.3'
services:
  jupyter:
    environment:
      - SHELL=/bin/bash
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
     - type : bind
       source: ./
       target: /app/
    hostname:
        docker-conda-poetry
    ports:
      - "8889:8889"
    command: conda run -n py376 --no-capture-output jupyter lab --ip="0.0.0.0" --port=8889 --no-browser --allow-root
    container_name: docker-conda-poetry